# generated by datamodel-codegen:
#   filename:  deprecated.json
#   timestamp: 2024-02-16T16:46:55+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import semver


class Deprecated(BaseModel):
    """
    An annotation marking an attribute or object as deprecated.
    """

    model_config = ConfigDict(
        extra='forbid',
    )
    message: str = Field(
        ..., description='A message that explains the deprecation to implementors.'
    )
    since: semver.SemVer = Field(
        ...,
        description='The version after which this attribute or object is deprecated.',
    )
