# generated by datamodel-codegen:
#   filename:  observable.json
#   timestamp: 2024-02-16T16:46:55+00:00

from __future__ import annotations

from pydantic import Field, RootModel, conint


class Observable(RootModel[conint(ge=0)]):
    root: conint(ge=0) = Field(
        ...,
        description='Adding `observable` includes this attribute or type in the list of Observable value types. This field must be unique across all usages. See the `type_id` field of the Observable object for more details.',
        title='Observable',
    )
